configRepo:
  url: "https://github.com/your-org/dbxplorer-inventory.git"
  branch: "main"
  username: "${CONFIG_REPO_USER}"
  password: "${CONFIG_REPO_TOKEN}"

datadog:
  apiKey: "${DD_API_KEY}"
  appKey: "${DD_APP_KEY}"
  userId: "<EMAIL>"
  url: "${DD_URL}"
  parallel: ${DD_PARALLEL}
  upload: ${DD_UPLOAD}

thread:
  worker: 5

license:
  key: "${AGENT_LICENSE_KEY}"

debug:
  pod: false
