# Datadog Secret for dbxplorer agent
apiVersion: v1
kind: Secret
metadata:
  name: dbxagent-env
  namespace: dbxplorer
type: Opaque
stringData:
  DD_API_KEY: "<your-datadog-api-key>"
  DD_APP_KEY: "<your-datadog-app-key>"
  DD_URL: "https://api.datadoghq.com"
  DD_PARALLEL: "200"
  DD_UPLOAD: "true"
  DD_AGENT_HOST: "datadog-agent"
  DD_TRACE_AGENT_PORT: "8126"
